- hosts: terraform-ansible
  tasks:
  - name: installing python3 in virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: installing dependencies (pip)
    pip:
      virtualenv: /home/ubuntu/backend/venv
      name: 
        - django
        - djangorestframework
  - name: starting project
    shell: '. /home/ubuntu/backend/venv/bin/activate; django-admin startproject setup /home/ubuntu/backend/'
    ignore_errors: yes
  - name: adjusting host settings
    lineinfile:
      path: /home/ubuntu/backend/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes