- hosts: terraform-ansible
  tasks:
  - name: creating file
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Made with Terraform and Ansible</h1>
  - name: creating server
    shell: "nohup busybox httpd -f -p 8080 &"