- hosts: terraform-ansible
  tasks:
  - name: installing python3 in virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: installing dependencies (pip)
    pip:
      virtualenv: /home/ubuntu/backend/venv
      name: 
        - django
        - djangorestframework